djangoal/urls.py
from django.conf.urls import url, include
from django.contrib import admin

from . import views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', views.HomeView.as_view(), name='home'),
    url(r'^hello/$', views.HelloWorldView.as_view(), name='home'),
    url(r'teams/', include('teams.urls', namespace='teams')),
]

teams/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.TeamListView.as_view(), name='list'),
    url(r'^(?P<pk>\d+)/$', views.TeamDetailView.as_view(), name='detail'),
    url(r'^create/$', views.TeamCreateView.as_view(), name='create'),
    url(r'^edit/(?P<pk>\d+)/$', views.TeamUpdateView.as_view(), name='update'),
    url(r'^delete/(?P<pk>\d+)/$', views.TeamDeleteView.as_view(), name='delete'),

    url(r'^player/$', views.PlayerListView.as_view(), name='players'),
]

teams/models.py
from django.contrib.auth.models import User
from django.db import models
from django.core.urlresolvers import reverse

POSITIONS = (
    ('GK', 'Goalkeeper'),
    ('CB', 'Center fullback'),
    ('SW', 'Sweeper'),
    ('LFB', 'Left fullback'),
    ('RFB', 'Right fullback'),
    ('WB', 'Wingback'),
    ('LM', 'Left midfield'),
    ('RM', 'Right midfield'),
    ('DM', 'Defensive midfield'),
    ('CM', 'Center midfield'),
    ('WM', 'Wide midfield'),
    ('CF', 'Center forward'),
    ('AM', 'Attacking midfield'),
    ('S', 'Striker'),
    ('SS', 'Second striker'),
    ('LW', 'Left winger'),
    ('RW', 'Right winger'),

)


class Team(models.Model):
    name = models.CharField(max_length=255)
    coach = models.ForeignKey(User, related_name='teams')
    practice_location = models.CharField(max_length=255)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        # After greation of model this will be called
        return reverse("teams:detail", kwargs={"pk": self.pk})


class Player(models.Model):
    name = models.CharField(max_length=255)
    age = models.PositiveIntegerField()
    position = models.CharField(choices=POSITIONS, max_length=3)
    team = models.ForeignKey(Team, related_name='players')

    def __str__(self):
        return self.name

djangoal/views.py
from django.http import HttpResponse
from django.shortcuts import render
from django.views.generic import View, TemplateView


def home(request):
    return render(request, 'home.html')


class HomeView(TemplateView):
    template_name = 'home.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["games_today"] = 6
        return context


class HelloWorldView(View):

    @staticmethod
    def get(request):
        return HttpResponse("Hello CBV !")

teams/views.py
from django.core.urlresolvers import reverse_lazy
from django.shortcuts import render, get_object_or_404
from django.views.generic import (
    ListView,
    DetailView,
    CreateView,
    UpdateView,
    DeleteView,
)
from . import models


class PlayerListView(ListView):
    model = models.Player


def team_list(request):
    teams = models.Team.objects.all()
    return render(request, 'teams/team_list.html', {'teams': teams})


def team_detail(request, pk):
    team = get_object_or_404(models.Team, pk=pk)
    return render(request, 'teams/team_detail.html', {'team': team})


class TeamListView(ListView):
    # Default template name is team_list.html ie: model_name_list.html
    model = models.Team
    context_object_name = "teams"


class TeamDetailView(DetailView):
    # Default template name is team_detail.html ie: model_name_detail.html
    # Also pk is the default arg passed to detail view
    model = models.Team


class TeamCreateView(CreateView):
    # Default template name is team_form.html ie: model_name_form.html
    # Can be overridden by template_name = "teams/team_form.html"
    model = models.Team
    fields = ["name", "practice_location", "coach"]  # requires field attr to which need to be included


class TeamUpdateView(UpdateView):
    fields = ["name", "practice_location", "coach"]
    model = models.Team


class TeamDeleteView(DeleteView):
    model = models.Team
    success_url = reverse_lazy("teams:list")

teams/templates/teams/_layout.html
{% extends "_layout.html" %}

{% block sidebar_content %}
    <ul class="nav nav-sidebar">
        <li class="active"><a href="#">Overview
            <span class="sr-only">(current)</span></a></li>
        <li><a href="#">Reports</a></li>
        <li><a href="#">Analytics</a></li>
        <li><a href="#">Export</a></li>
    </ul>
    <ul class="nav nav-sidebar">
        <li><a href="{% url 'teams:create' %}"><span class="glyphicon glyphicon-plus" aria-hidden="true"></span> Add new
            team</a></li>
    </ul>
{% endblock %}

teams/templates/teams/_team.html
<div class="col-xs-6 col-sm-3 placeholder">
	<a href="{% url 'teams:detail' team.pk %}">
		<i class="avatar avatar-lg avatar-color-{{ num }} avatar-letter-{{ team.name.0|lower }} rounded"></i>
		<h4>{{ team.name }}</h4>
		<span class="text-muted">{{ team.players.count }} player{{ team.players.count|pluralize }}</span>
	</a>
</div>

teams/templates/teams/player_list.html
{% extends '_layout.html' %}

{% block body_content %}

    <div class="row">
        <div class="col-md-6">
            {% for player in object_list %}
                <div class="panel panel-default">
                    <div class="panel-heading"><b>{{ player.name }}</b></div>
                    <div class="panel-body">
                        <ul>
                            <li>Team :{{ player.team }}</li>
                            <li>Age : {{ player.age }}</li>
                            <li>Position : {{ player.position }}</li>
                        </ul>
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>
{% endblock body_content %}

teams/templates/teams/team_confirm_delete.html
{% extends '_layout.html' %}
{% block body_content %}
    <h1>Delete {{ team.name }}</h1>
    <form action="" method="post">
        {% csrf_token %}
        <input type="submit" value="Delete" class="btn btn-danger">
        <a href="{% url 'teams:detail' pk=team.pk %}">Cancel</a>
    </form>
{% endblock body_content %}

teams/templates/teams/team_detail.html
{% extends "teams/_layout.html" %}

{% block body_content %}
    <h1>{{ team.name }}</h1>
    <p class="muted">{{ team.practice_location }}</p>
    <p>Coached by <strong>{{ team.coach.get_full_name|default:team.coach }}</strong></p>

    <h2>Players</h2>
    <ul>
        {% for player in team.players.all %}
            <li>{{ player.name }} - {{ player.get_position_display }}</li>
        {% endfor %}
    </ul>
    <hr>
    <p>
        <a href="{% url 'teams:update' pk=team.pk %}" class="btn btn-primary">Edit</a>
    </p>
    <p>
        <a href="{% url 'teams:delete' pk=team.pk %}" class="btn btn-danger">Delete</a>
    </p>
{% endblock %}

teams/templates/teams/team_form.html
{% extends "teams/_layout.html" %}

{% block body_content %}
    <h1>{% if not form.instance.pk %}Create Team{% else %} Edit {% endif %}</h1>
    <form action="" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Ok" class="btn btn-primary">
    </form>
{% endblock body_content %}

teams/templates/teams/team_list.html
{% extends "teams/_layout.html" %}
{% load static from staticfiles %}
{% load team_tags %}

{% block css %}
<link rel="stylesheet" href="{% static 'css/icons.css' %}">
{% endblock %}

{% block body_content %}
<h1 class="page-header">Dashboard</h1>
<div class="row placeholders">
	{% for team in teams %}
		{% team_avatar team %}
	{% endfor %}
</div>
{% endblock %}

templates/_layout.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->

        {% load static from staticfiles %}
        <title>{% block title_tag %}Goal!{% endblock %}</title>

        <!-- Bootstrap core CSS -->
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">
		{% block css %}{% endblock %}
        <link rel="stylesheet" href="{% static 'css/goal.css' %}">
        <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries --><!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
        <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
        <![endif]-->
    </head>
    <body>
        <nav class="navbar navbar-inverse navbar-fixed-top">
            <div class="container-fluid">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="#">Goal! Soccer Team Organizer</a>
                </div>
                <div id="navbar" class="navbar-collapse collapse">
                    <ul class="nav navbar-nav navbar-right">
						<li><a href="{% url 'teams:list' %}">Teams</a></li>
                        <li><a href="#">Settings</a></li>
                        <li><a href="#">Help</a></li>
                    </ul>
                    <form class="navbar-form navbar-right">
                        <input type="text" class="form-control" placeholder="Search...">
                    </form>
                </div>
            </div>
        </nav>
        <div class="container-fluid">
            <div class="row">
				{% block sidebar %}
                <div class="col-sm-3 col-md-2 sidebar">
					{% block sidebar_content %}{% endblock %}
                </div>
				{% endblock %}
                <div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">
                    {% block body_content %}{% endblock %}
                </div>
            </div>
        </div>
        <script src="https://code.jquery.com/jquery-2.2.4.min.js"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js" integrity="sha384-0mSbJDEHialfmuBBQP6A4Qrprq5OVfW37PRR3j5ELqxss1yVqOtnepnHVP9aJ7xS" crossorigin="anonymous"></script>
    </body>
</html>

templates/home.html
{% extends "_layout.html" %}

{% block sidebar %}{% endblock %}

{% block body_content %}
    <div class="jumbotron">
        <h1>Goal!</h1>
        <p>This is the easiest way to keep track of your soccer team(s) and players!</p>
        <p>
            <a href="#" role="button" class="btn btn-default btn-lg">Sign up</a> or
            <a href="#" role="button" class="btn btn-default btn-lg">Log in</a>
            <b>Today there {{ games_today|pluralize:'is,are' }} {{ games_today }} game{{ games_today|pluralize }} </b>
        </p>
    </div>
{% endblock %}